apiVersion: v1
kind: Pod
metadata:
  name: openshift
  labels:
    mycka: simplilearn
spec:
  containers:
  - name: mycontainer2
    image: openshift/hello-openshift
    ports:
    - containerPort: 80

