---
- name: User Account Management
  hosts: all
  become: true
  tasks:
    - name: adding group
      group:
        name: wheel
        state: present
    - name: add several users
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: 'testuser1', groups: 'wheel' }
        - { name: 'testuser2', groups: 'root' }

