---
- name: Testing ping module
  hosts: all
  become: true
  tasks:

  - name: installing apache2
    apt:
      name: apache2
      state: latest
    tags: myapache2

  - name: installing telnet
    apt:
      name: telnet
      state: latest
    tags: mytelnet

  - name: adding index.html
    copy:
      src: myindex.html
      dest: /var/www/html/index.html
    tags: myapache2

  - name: restarting apache2 service
    service:
      name: apache2
      state: restarted

  - name: adding users
    user: 
      name: myuser10
      state: present

