---
- name: User Account Management
  hosts: all
  become: true
  tasks:
    - name: Add simplilearn User Group
      group:
        name: simplilearn
    - name: Adding Users....
      user:
        name: "{{ item }}"
        state: present
      loop:
        - user1
        - user2
        - user3

